name: Test
on: [push]
jobs:
    test:
        strategy:
            matrix:
                julia-version: ['1.5.0']
                python-version: ['3.6']
                os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@latest
              with:
                version: ${{ matrix.julia-version }}
            - name: Install python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install numpy
            - uses: julia-actions/julia-buildpkg@latest
            - uses: julia-actions/julia-runtest@latest
